{"name": "test_divide[2-4-5]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0.5 == 5\n  +0.5\n  -5", "trace": "self = <test_calculator.TestCalculator object at 0x0000017CA0D75610>, a = 2, b = 4, exc = 5\n\n    @pytest.mark.parametrize('a,b, exc', [\n        (1, 2, 3),\n        (2, 4, 5),\n        (4, 7, 11)\n    ])\n    def test_divide(self, a, b, exc):\n        if b != 0:\n            result = self.c.divide(a, b)\n>           assert result == exc\nE           assert 0.5 == 5\nE             +0.5\nE             -5\n\ntest_calculator.py:55: AssertionError"}, "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "4"}, {"name": "exc", "value": "5"}], "start": 1615726260909, "stop": 1615726260909, "uuid": "2a5f9271-1a27-49e3-a2de-b104f3f5f8d2", "historyId": "be9e2c4253776bdd8217bc69dd095ae9", "testCaseId": "2c8d772870fd08f5fb143f47cbd63015", "fullName": "test_calculator.TestCalculator#test_divide", "labels": [{"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}