{"name": "test_divide[1-2-3]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0.5 == 3\n  +0.5\n  -3", "trace": "self = <test_calculator.TestCalculator object at 0x0000017CA0D77D00>, a = 1, b = 2, exc = 3\n\n    @pytest.mark.parametrize('a,b, exc', [\n        (1, 2, 3),\n        (2, 4, 5),\n        (4, 7, 11)\n    ])\n    def test_divide(self, a, b, exc):\n        if b != 0:\n            result = self.c.divide(a, b)\n>           assert result == exc\nE           assert 0.5 == 3\nE             +0.5\nE             -3\n\ntest_calculator.py:55: AssertionError"}, "parameters": [{"name": "a", "value": "1"}, {"name": "b", "value": "2"}, {"name": "exc", "value": "3"}], "start": 1615726260915, "stop": 1615726260915, "uuid": "25e8c079-523a-4b99-b415-69abf9985cc1", "historyId": "536bd275ea0ab024f3794af870fa3fac", "testCaseId": "2c8d772870fd08f5fb143f47cbd63015", "fullName": "test_calculator.TestCalculator#test_divide", "labels": [{"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "FDD-PZSTWIEXCFJ"}, {"name": "thread", "value": "2028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator"}]}